spring.application.name=ConsentService

server.port=8084

spring.data.mongodb.uri=mongodb://localhost:27017/test

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Register using IP instead of Windows hostname
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1