spring.application.name=PatientService

# ==========================
# Server Configuration
# ==========================
server.port=8090

# ==========================
# MongoDB Configuration
# ==========================
spring.data.mongodb.uri=mongodb://localhost:27017/patientdb

# ==========================
# Eureka Client Configuration
# ==========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# ==========================
# Logging
# ==========================
logging.level.org.springframework=INFO
logging.level.com.infosys=DEBUG